main:
  - name: About
    url: /#about
    weight: 10
  - name: Publications
    url: /#publications
    weight: 20
  - name: Projects
    url: /#projects
    weight: 30
  - name: News
    url: /#news
    weight: 40
  - name: Experience
    url: experience/
    weight: 50
